#!/bin/sh
#PBS -l select=2:system=polaris
#PBS -l place=scatter
#PBS -l walltime=10:00
#PBS -q debug
#PBS -A radix-io
time /home/hyoklee/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/fabtsuite-main-i6u2p2n6znlovf74rnff6nvgfctvn66c/bin/fabtget -a /home/hyoklee/address.txt &
sleep 3 && { time -p /home/hyoklee/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/fabtsuite-main-i6u2p2n6znlovf74rnff6nvgfctvn66c/bin/fabtput $(cat /home/hyoklee/address.txt); }  &> /home/hyoklee/put.out

